name: Update LG Channels

on:
#  schedule:
    # Runs at 03:20, 09:20, 15:20, 21:20 UTC every day
#    - cron: '20 3,9,15,21 * * *'
  workflow_dispatch: # Allows you to run the workflow manually from the GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Scraper Script
        run: |
          python run_lg.py

      - name: Commit and Push Generated M3U and XMLTV files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add lg_playlist.m3u lg.xml
          git commit -m "Automated update: LG Channels Playlist & EPG [skip ci]"
          git push
          
